version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - webnet

  frontend:
    build: ./frontend
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
