version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
